admin_panel/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('admin_login', views.admin_login, name='admin_login'),
    path('admin_panel', views.admin_panel, name='admin_panel'),
    path('logout', views.log_out, name='logout'),
    path('user-management', views.user_management, name='user_management'),
    path('user-management/user_search', views.user_search, name='user_search'),
    path('user-management/block_user/<pk>', views.block_user, name='block_user'),
    path('user-management/unblock_user/<pk>', views.unblock_user, name='unblock_user'),
    path('category-management', views.category_management, name='category_management'),
    path('category-management/category-unlist/<pk>', views.unlist_category, name='unlist_category'),
    path('category-management/category-list/<pk>', views.list_category, name='list_category'),
    path('category-management/add_category', views.add_category, name='add_category'),
    path('category-management/edit_category/<pk>', views.edit_category, name='edit_category'),
    path('category-management/category_search', views.category_search, name='category_search'),
    path('product-management', views.product_management, name='product_management'),
    path('product-management/product-unlist/<pk>', views.unlist_product, name='unlist_product'),
    path('product-management/product-list/<pk>', views.list_product, name='list_product'),
    path('product-management/add_product', views.add_product, name='add_product'),
    path('product-management/edit_product/<pk>', views.edit_product, name='edit_product'),
    path('product-management/product_search', views.product_search, name='product_search'),
    path('variant-management', views.variant_management, name='variant_management'),
    path('variant-management/add_variant', views.add_variant, name='add_variant'),
    path('variant-management/edit_variant/<pk>', views.edit_variant, name='edit_variant'),
    path('variant-management/variant_search', views.variant_search, name='variant_search'),
    path('coupon-management/', views.coupon_management, name='coupon_management'),
    path('coupon-management/add-coupon', views.add_coupon, name='add_coupon'),
    path('coupon-management/unlist-coupon/<pk>', views.unlist_coupon, name='unlist_coupon'),
    path('coupon-management/list-coupon/<pk>', views.list_coupon, name='list_coupon'),
    path('coupon-management/edit-coupon/<pk>', views.edit_coupon, name='edit_coupon'),
    path('order-management/', views.order_management, name='order_management'),
    path('order-management/order-details/<int:order_id>', views.order_details, name='order_details'),
    path('order-management/cancel-order/<int:order_id>', views.cancel_order, name='cancel_order'),
    path('order-management/order-search', views.order_search, name='order_search'),
    path('offer-management/', views.offer_management, name='offer_management'),
    path('offer-management/add-offer/', views.add_offer, name='add_offer'),
    path('offer-management/edit-offer/<int:offer_id>', views.edit_offer, name='edit_offer'),
    path('offer-management/activate-coupon/<pk>', views.activate_offer, name='activate_offer'),
    path('offer-management/deactivate-coupon/<pk>', views.deactivate_offer, name='deactivate_offer'),
    path('sales-report/', views.sales_report, name='sales_report'),
    path('sales-report-pdf/', views.sales_report_pdf, name='sales_report_pdf'),
    path('sales-report-excel/', views.sales_report_excel, name='sales_report_excel'),
    path('admin_panel/get_sales_data/<period>/', views.get_sales_data, name='get_sales_data'),


]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='home'),
    path('dashboard/main/', views.dashboard, name='dashboard'),
    path('dashboard/my-orders/', views.my_orders, name='my_orders'),
    path('dashboard/my-orders/order-detail/<int:order_id>', views.order_detail, name='order_detail'),
    path('dashboard/cancel-orders/<int:order_id>', views.cancel_orders, name='cancel_orders'),
    path('dashboard/change-password/', views.change_password, name='change_password'),
    path('dashboard/account-details/', views.update_account_details, name='update_account_details'),
    path('dashboard/wallet/', views.wallet, name='wallet'),
    path('dashboard/my-address/', views.my_address, name='my_address'),
    path('dashboard/add-address/', views.add_address, name='add_address'),
    path('dashboard/edit-address/<int:address_id>', views.edit_address, name='edit_address'),
    path('dashboard/select-address/<int:address_id>', views.select_address, name='select_address'),
    path('dashboard/delete-address/<int:address_id>', views.delete_address, name='delete_address'),
    path('about/',views.about, name='about'),
    path('faq/',views.faq, name='faq'),
    path('contact-us/',views.contact_us, name='contact_us'),

]

urbanwrap_ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('admin_panel.urls')),
    path('', include('user_auth.urls')),
    path('', include('shop.urls')),
    path('orders/', include('orders.urls')),
    path('', include('paypal.standard.ipn.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from user_auth.models import User
from email.policy import default
from django.db import models
from home.models import Product, Variation
from datetime import timezone
from django.core.exceptions import ValidationError
from django.utils import timezone as tz
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.payment_id
    

class Order(models.Model):

    STATUS = (
        ('New','New'),
        ('Accepted','Accepted'),
        ('Completed','Completed'),
        ('Cancelled','Cancelled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20) 
    first_name = models.CharField(max_length=50) 
    last_name = models.CharField(max_length=50) 
    phone = models.CharField(max_length=15) 
    email = models.EmailField(max_length=50) 
    address_line_1 = models.CharField(max_length=50) 
    address_line_2 = models.CharField(max_length=50) 
    country = models.CharField(max_length=50) 
    state = models.CharField(max_length=50) 
    city = models.CharField(max_length=50) 
    pin_code = models.IntegerField()
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.DecimalField(max_digits=10, decimal_places=2)
    tax = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    payment_method=models.CharField(max_length=15) 
    ip = models.CharField(max_length=20, blank=True)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)        
    updated_at = models.DateTimeField(auto_now=True)


    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    
    def full_address(self):
        return f'{self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.first_name
    
@receiver(post_save, sender=Order)
def update_payment_status(sender, instance, **kwargs):
    if instance.status == 'Completed' and instance.payment:
        instance.payment.status = 'Completed'
        instance.payment.save()
    

class OrderProduct(models.Model):

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation,blank=True)
    quantity = models.IntegerField()
    product_price = models.DecimalField(max_digits=10, decimal_places=2)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)        
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name
     
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    


class Wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    card_id = models.CharField(max_length=12, unique=True)
    balance = models.DecimalField(default=0, max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.user.username}'s Wallet"
    

class WalletTransaction(models.Model):
    TRANSACTION_TYPES = (
        ('debit', 'Debit'),
        ('credit', 'Credit'),
    )

    transaction_id = models.CharField(max_length=12, unique=True)
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPES)
    order_reference = models.ForeignKey('Order', on_delete=models.SET_NULL, blank=True, null=True)
    updated_balance = models.DecimalField(max_digits=10, decimal_places=2) 
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.wallet.user.username}'s {self.get_transaction_type_display()} transaction of {self.amount}"
    

class Offer(models.Model):
    name = models.CharField(max_length=100)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2)
    valid_from = models.DateTimeField(auto_now_add=True)
    valid_to = models.DateField()
    products = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True, related_name='product')
    is_active= models.BooleanField(default=True)

    def __str__(self):
        return self.name
    

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.products:
            self.products.is_sale = True
            discount_amount = self.products.price * (self.discount_percentage / 100)
            self.products.discounted_price = self.products.price - discount_amount
            self.products.save()

    def clean(self):
        if self.valid_to is not None and self.valid_to < tz.now().date():
            raise ValidationError({'valid_to': "Valid to date must be in the future."})
        
        if self.valid_from is not None and self.valid_to is not None and self.valid_from > self.valid_to:
            raise ValidationError({'valid_from': "Valid from date must be before valid to date."})
        

@receiver(post_save, sender=Offer)
def update_product_on_offer_creation(sender, instance, created, **kwargs):
    if created:
        if instance.products:
            instance.products.is_sale = True
            discount_amount = instance.products.price * (instance.discount_percentage / 100)
            instance.products.discounted_price = instance.products.price - discount_amount
            instance.products.save()

admin_panel/forms.py
from django import forms 
from user_auth.models import User, Coupon
from home.models import Category, Product, Variation, ProductImages
from orders.models import Order, Offer
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
from django.utils import timezone


class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name')



class AddCategoryForm(forms.ModelForm):
    cat_image = forms.ImageField(validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], required=False)
    class Meta:
        model = Category
        fields = ('category_name', 'slug', 'description', 'cat_image')




class AddProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('product_name', 'slug', 'description', 'price', 'is_available', 'category')




class AddVariantForm(forms.ModelForm):

    class Meta:
        model = Variation
        fields = ('product', 'variation_category', 'variation_value', 'is_active', 'stock')


class ProductImageForm(forms.ModelForm):
    image = forms.ImageField(validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], )
    delete_image = forms.BooleanField(required=False, initial=False, widget=forms.CheckboxInput(attrs={'class': 'delete-checkbox'}))
    class Meta:
        model = ProductImages
        fields =('image','delete_image')

   
class AddCouponForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = ('coupon_code', 'discounted_price', 'minimum_amount', 'is_expired')

    def clean(self):
            cleaned_data = super().clean()
            discounted_price = cleaned_data.get('discounted_price')
            minimum_amount = cleaned_data.get('minimum_amount')

            if discounted_price is not None and minimum_amount is not None:
                if discounted_price >= minimum_amount:
                    raise forms.ValidationError("Discounted price should be less than the minimum amount.")

            return cleaned_data
    
    
class UpdateOrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('status',)


class AddOfferForm(forms.ModelForm):
    discount_percentage = forms.DecimalField(min_value=0, max_value=100)

    class Meta:
        model = Offer
        fields = ('name', 'discount_percentage', 'valid_to', 'products')

    def clean_valid_to(self):
        valid_to = self.cleaned_data.get('valid_to')
        if valid_to < timezone.now().date():
            raise ValidationError("Valid to date must be in the future.")
        return valid_to

templates/admin_panel/add_category.html
{% extends 'partials/base_admin.html' %}


{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
          <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                  <div class="card-body">
                      <h4 class="card-title">Add Category</h4>
                      <div class="container">
                        <div class="row justify-content-center">
                          <div class="col-12 col-md-9 col-lg-7 col-xl-6 col-xxl-5">
                            <div class="card border-0 shadow">
                              <div class="card-body p-3 p-md-4 p-xl-5">
                                <div class="row">
                                  <div class="col-12">
                                    <div class="mb-5">
                                      <h3 class="text-center text-uppercase">Create Category</h3>
                                    </div>
                                  </div>
                                </div>
                              
                                <form action="" method="post" enctype="multipart/form-data">
                                  {% csrf_token %}
                                  <div class="row gy-3 overflow-hidden">
                                    <div class="col-12">
                                      <div class="form-floating mb-3">
                                        <label for="categoryName" class="form-label">Category name</label>
                                        <input type="{{ form.category_name.field.widget.input_type }}"
                                        name="{{ form.category_name.name }}"
                                        id="categoryName"
                                        class="form-control text-light" required>
                                      </div>
                                    </div>
                                    <div class="col-12">
                                      <div class="form-floating mb-3">
                                        <label for="slug" class="form-label">Slug</label>
                                        <input type="{{ form.slug.field.widget.input_type }}"
                                        name="{{ form.slug.name }}"
                                        id="slug"
                                        class="form-control text-light"  required>
                                      </div>
                                    </div>
                                    <div class="col-12">
                                      <div class="form-floating mb-3">
                                        <label for="description" class="form-label">Description</label>
                                        <input type="{{ form.description.field.widget.input_type }}"
                                        name="{{ form.description.name }}"
                                        id="{{ form.description.id_for_label }}"
                                        class="form-control text-light" >
                                      </div>
                                    </div>
                                    <div class="col-12">
                                      <div class="form-floating mb-3">
                                        <label for="cat_image" class="form-label">Category Image</label>
                                        <input type="{{ form.cat_image.field.widget.input_type }}"
                                        name="{{ form.cat_image.name }}"
                                        id="{{ form.cat_image.id_for_label }}"
                                        class="form-control text-light" >
                                      </div>
                                    </div>
                                    <div class="col-12">
                                      <div class="d-grid">
                                        <button class="btn bsb-btn-2xl btn-primary " type="submit">Create</button> 
                                        <button class="btn bsb-btn-2xl btn-primary ml-5" type="button"><a href="{% url 'category_management' %}" class="text-light">Back</a></button>
                                    </div>
                                  </div>
                                </form>
                                {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                  <p class="text-center text-danger">{{ error }}</p>
                                {% endfor %}
                                {% endfor %}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
  $(document).ready(function() {
      function generateSlug(categoryName) {
          return categoryName.trim().toLowerCase().replace(/\s+/g, '-');
      }

      $('#categoryName').on('input', function() {
          var categoryName = $(this).val();
          var slug = generateSlug(categoryName);
          $('#slug').val(slug);
      });
  });
</script>
{% endblock content %}
    

templates/admin_panel/add_offer.html
{% extends 'partials/base_admin.html' %}


{% block content %}
<style>
  .errorlist{
    color: red;
    font-size: small;
    list-style: none;
    padding-left:0
  }
</style>
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
          <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                  <div class="card-body">
                      <h4 class="card-title">Add Offer</h4>
                      <div class="container">
                        <div class="row justify-content-center">
                          <div class="col-12 col-md-9 col-lg-7 col-xl-6 col-xxl-5">
                            <div class="card border-0 shadow">
                              <div class="card-body p-3 p-md-4 p-xl-5">
                                <div class="row">
                                  <div class="col-12">
                                    <div class="mb-5">
                                      <h3 class="text-center text-uppercase">Create Offer</h3>
                                    </div>
                                  </div>
                                </div>
                              
                                <form action="" method="post" enctype="multipart/form-data">
                                  {% csrf_token %}
                                  <div class="row gy-3 overflow-hidden">
                                    <div class="col-12">
                                      <div class="form-floating mb-3">
                                        <label for="category_name" class="form-label">Offer name</label>
                                        {{form.name}}
                                      </div>
                                      {% if error_name != None %}
                                        <p>{{error_name}}</p>
                                      {% endif %}
                                    </div>
                                    <div class="col-12">
                                      <div class="form-floating mb-3">
                                        <label for="slug" class="form-label">Discount percentage</label>
                                        {{form.discount_percentage}}
                                      </div>
                                      {% if error_discount_percentage != None %}
                                        <p>{{error_discount_percentage}}</p>
                                      {% endif %}
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating mb-3">
                                          <label for="variation_value" class="form-label">Valid to</label>
                                          {{form.valid_to}}
                                        </div>
                                        {% if error_valid_to != None %}
                                        <p>{{error_valid_to}}</p>
                                      {% endif %}
                                      </div>
                                      <div class="col-12">
                                        <div class="form-floating mb-3">
                                          <label for="variation_value" class="form-label">Products</label>
                                          {{form.products   }}
                                        </div>
                                      </div>
                                    <div class="col-12">
                                      <div class="d-grid">
                                        <button class="btn bsb-btn-2xl btn-primary " type="submit">Create</button> 
                                        <button class="btn bsb-btn-2xl btn-primary ml-5" type="button"><a href="{% url 'offer_management' %}" class="text-light">Back</a></button>
                                    </div>
                                  </div>
                                </form>
                                {% for message in messages %}
                                  <p class="text-danger">{{message}}</p>
                                  {% endfor %}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock content %}
    

templates/admin_panel/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body class="body">
    <link rel="stylesheet" href="{% static 'admin.css' %}">
    <section class="bg-white p-3 p-md-4 p-xl-5">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-12 col-md-9 col-lg-7 col-xl-6 col-xxl-5">
              <div class="card border-0 shadow">
                <div class="card-body p-3 p-md-4 p-xl-5">
                  <div class="row">
                    <div class="col-12">
                      <div class="mb-5">
                        <h3 class="text-center text-uppercase">Admin Login</h3>
                      </div>
                    </div>
                  </div>
                  <form action="" method="post">
                    {% csrf_token %}
                    <div class="row gy-3 overflow-hidden">
                      <div class="col-12">
                        <div class="form-floating mb-3">
                          <input type="email" class="form-control" name="email" id="email"  required>
                          <label for="email" class="form-label">Email</label>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="form-floating mb-3">
                          <input type="password" class="form-control" name="password" id="password" value=""  required>
                          <label for="password" class="form-label">Password</label>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="d-grid">
                          <button class="btn bsb-btn-2xl btn-dark" type="submit">Log in</button>
                        </div>
                      </div>
                    </div>
                  </form>
                  {% for message in messages %}
                    <p class="text-danger">{{message}}</p>
                  {% endfor %}
                  <div class="row">
                    <div class="col-12">
                      <hr class="mt-5 mb-4 border-secondary-subtle">
                      <div class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-end">
                        <a href="#!" class="link-secondary text-decoration-none text-primary">Forgot password</a>
                      </div>
                    </div>
                  </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/admin_panel/order_details.html
{% extends 'partials/base_admin.html' %}

{% block content %}
<div class="main-panel">
    <div class="content-wrapper">
      <div class="row">
          <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                  <div class="card-body">
                      <h4 class="card-title">Order Details</h4>
                      <div class="invoice-items mt-5">
                        <div class="table-responsive border border-1" style="overflow: hidden; outline: none;" tabindex="0">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th class="per70 text-center">Description</th>
                                        <th class="per5 text-center">Qty</th>
                                        <th class="per25 text-center">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    {% for item in order.orderproduct_set.all %}
                                        
                                    
                                    <tr>
                                        <td>{{item.product.product_name}}</td>
                                        <td class="text-center">{{item.quantity}}</td>
                                        <td class="text-center">${{item.product.price}}</td>
                                    </tr>
                                    
                                    {% endfor %}
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="2" class="text-right">Sub Total:</th>
                                        <th class="text-center">${{order_subtotal}}</th>
                                    </tr>
                                    <tr>
                                        <th colspan="2" class="text-right">Tax:</th>
                                        <th class="text-center">${{order.tax}}</th>
                                    </tr>
                                    <tr>
                                        <th colspan="2" class="text-right">Total:</th>
                                        <th class="text-center">${{order.order_total}} USD</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <h5 class="card-title mt-5">Order status</h4>
                            <form action="" method="POST">
                                {% csrf_token %}
                                {{order_update_form.as_p}}
                                <button type="submit" class="btn-inverse-info">Save</button>
                            </form>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock content %}
    